import { useCallback, useEffect, useRef, useState } from 'react';import { useNavigate, useParams } from 'react-router-dom';import { AnimatePresence, motion } from 'framer-motion';import { WifiOff, Check, X } from 'lucide-react';import type { PublicQuestion, PlayerResult, AnswerStats, LeaderboardEntry, AnswerIndex, GameStatus } from '@shared/types';import { getSocket, emitAck } from '@/socket/socket';import { session } from '@/utils/session';import { useServerClock } from '@/hooks/useServerClock';import { useCountdown } from '@/hooks/useCountdown';import { AnswerButton } from '@/components/AnswerButton';import { CountdownRing } from '@/components/CountdownRing';import { LeaderboardList } from '@/components/LeaderboardList';import { Confetti } from '@/components/Confetti';
type View = 'connecting' | 'lobby' | 'getready' | 'question' | 'result' | 'stats' | 'leaderboard' | 'ended' | 'error';
export default function Play() {  const { pin = '' } = useParams(); const nav = useNavigate();  const sess = session.load(pin);  const { sync, now } = useServerClock();
  const [view, setView] = useState<View>('connecting');  const [q, setQ] = useState<PublicQuestion | null>(null);  const [selected, setSelected] = useState<AnswerIndex | null>(null);  const [result, setResult] = useState<PlayerResult | null>(null);  const [stats, setStats] = useState<AnswerStats | null>(null);  const [lb, setLb] = useState<{ top: LeaderboardEntry[]; you?: LeaderboardEntry } | null>(null);  const [score, setScore] = useState(0);  const [offline, setOffline] = useState(false);  const [err, setErr] = useState(''); const [toast, setToast] = useState('');  const { secondsLeft, progress } = useCountdown(q?.endsAt ?? null, q?.startsAt ?? null, now);  const submitting = useRef(false);
  const statusToView = (s: GameStatus): View =>    ({ LOBBY: 'lobby', QUESTION: 'question', QUESTION_ENDED: 'result', STATS: 'stats', LEADERBOARD: 'leaderboard', ENDED: 'ended' } as const)[s];
  const restore = useCallback(async () => {    if (!sess) { nav(`/join?pin=${pin}`, { replace: true }); return; }    const r = await emitAck('reconnect-player', { pin, token: sess.token });    if (!r.ok) { session.clear(pin); setErr(r.message); setView('error'); return; }    setScore(r.data.score); setOffline(false);    if (r.data.question) { sync(r.data.question.serverNow); setQ(r.data.question); setSelected(r.data.alreadyAnswered ? (-1 as any) : null); }    setView(statusToView(r.data.status));  }, [pin, sess, nav, sync]);
  useEffect(() => {    const s = getSocket();    const onConnect = () => restore();    if (s.connected) restore(); else s.once('connect', onConnect);    s.on('connect', () => setOffline(false));    s.on('disconnect', () => setOffline(true));    s.io.on('reconnect', () => restore());
    s.on('game-started', () => { setView('getready'); });    s.on('question-started', pq => { sync(pq.serverNow); setQ(pq); setSelected(null); setResult(null); setStats(null); setView('question'); });    s.on('question-ended', () => setView(v => (v === 'question' ? 'result' : v)));    s.on('player-result', r => { setResult(r); setScore(r.totalScore); setView('result'); if (navigator.vibrate) navigator.vibrate(r.correct ? [40, 40, 40] : 120); });    s.on('show-results', st => { setStats(st); setView('stats'); });    s.on('show-leaderboard', p => { setLb(p); setView('leaderboard'); });    s.on('game-ended', p => { setLb(p); setView('ended'); });    s.on('host-disconnected', () => setToast('Host disconnected — waiting for them to return…'));    s.on('host-reconnected', () => setToast(''));    s.on('kicked', () => { session.clear(pin); setErr('You were removed from the game by the host.'); setView('error'); });    return () => { s.off('connect', onConnect); s.removeAllListeners(); s.io.off('reconnect'); };  }, [pin, restore, sync]);
  const answer = async (i: AnswerIndex) => {    if (!q || selected !== null || submitting.current) return;    submitting.current = true; setSelected(i);    const r = await emitAck('submit-answer', { pin, questionIndex: q.index, answer: i });    submitting.current = false;    if (!r.ok) { if (r.code === 'DUPLICATE_ANSWER') return; setSelected(null); setToast(r.message); setTimeout(() => setToast(''), 2500); }  };
  const nickname = sess?.nickname ?? '';  const hasAnswered = selected !== null;
  return (    <main className="flex min-h-full flex-col bg-slate-950">      {/* top bar */}      <header className="flex items-center justify-between px-4 py-3 text-sm">        <span className="font-semibold text-white/80">{nickname}</span>        <span className="rounded-full bg-white/10 px-3 py-1 font-display font-bold tabular-nums">{score.toLocaleString()}</span>      </header>      {offline && <div className="flex items-center justify-center gap-2 bg-amber-500/20 py-2 text-sm text-amber-300"><WifiOff className="h-4 w-4" /> Reconnecting…</div>}      {toast && <div className="bg-white/10 py-2 text-center text-sm">{toast}</div>}
      <section className="flex flex-1 flex-col px-4 pb-6">        <AnimatePresence mode="wait">          {view === 'connecting' && <Center key="c"><p className="text-white/60">Connecting…</p></Center>}
          {view === 'lobby' && (            <Center key="l">              <motion.div animate={{ scale: [1, 1.06, 1] }} transition={{ repeat: Infinity, duration: 2 }} className="text-6xl">🎉</motion.div>              <h1 className="mt-4 font-display text-3xl font-extrabold">You're in!</h1>              <p className="mt-2 text-white/60">See your nickname on the screen? Waiting for the host to start…</p>            </Center>          )}
          {view === 'getready' && <Center key="g"><motion.h1 initial={{ scale: .5 }} animate={{ scale: 1 }} className="font-display text-5xl font-extrabold">Get ready!</motion.h1></Center>}
          {view === 'question' && q && (            <motion.div key={`q${q.index}`} initial={{ opacity: 0, x: 40 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -40 }} className="flex flex-1 flex-col">              <div className="mb-3 flex items-center justify-between text-sm text-white/60">                <span>Question {q.index + 1} / {q.total}</span><CountdownRing secondsLeft={secondsLeft} progress={progress} size={64} />              </div>              <h2 className="mb-4 font-display text-xl font-bold leading-snug md:text-3xl">{q.text}</h2>              {q.imageUrl && <img src={q.imageUrl} alt="" className="mb-4 max-h-56 w-full rounded-2xl object-cover" />}              {hasAnswered ? (                <Center><motion.div initial={{ scale: .8 }} animate={{ scale: 1 }} className="text-center">                  <div className="text-5xl">⚡</div><p className="mt-3 font-display text-2xl font-bold">Answer locked in!</p><p className="text-white/60">Waiting for others…</p></motion.div></Center>              ) : (                <div className="mt-auto grid grid-cols-1 gap-3 md:grid-cols-2">                  {([0, 1, 2, 3] as AnswerIndex[]).map(i => <AnswerButton key={i} index={i} text={q.options[i]} onSelect={answer} disabled={secondsLeft <= 0} />)}                </div>              )}            </motion.div>          )}
          {view === 'result' && (            <Center key="r">              {result ? (                <motion.div initial={{ scale: .7, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} transition={{ type: 'spring', stiffness: 300 }}                  className={`w-full max-w-sm rounded-3xl p-8 text-center ${result.correct ? 'bg-emerald-500' : 'bg-rose-500'}`}>                  {result.correct ? <Check className="mx-auto h-16 w-16" strokeWidth={3} /> : <X className="mx-auto h-16 w-16" strokeWidth={3} />}                  <h2 className="mt-3 font-display text-3xl font-extrabold">{result.correct ? 'Correct!' : 'Not quite'}</h2>                  {result.correct && result.streak > 1 && <p className="mt-1 font-semibold">🔥 {result.streak} answer streak</p>}                  <p className="mt-4 font-display text-2xl font-bold">+{result.pointsEarned}</p>                  <p className="text-sm opacity-80">You're in {ordinal(result.rank)} place</p>                </motion.div>              ) : <p className="text-white/60">Time's up! Waiting for results…</p>}            </Center>          )}
          {view === 'stats' && stats && q && (            <motion.div key="s" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-3">              <h2 className="font-display text-xl font-bold">{q.text}</h2>              {([0, 1, 2, 3] as AnswerIndex[]).map(i => <AnswerButton key={i} index={i} text={q.options[i]} compact disabled                selected={selected === i} reveal={i === stats.correctIndex ? 'correct' : 'wrong'} />)}            </motion.div>          )}
          {view === 'leaderboard' && lb && (            <motion.div key="lb" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>              <h2 className="mb-4 text-center font-display text-3xl font-extrabold">Leaderboard</h2>              <LeaderboardList entries={lb.top} highlightId={sess?.playerId} />              {lb.you && !lb.top.some(t => t.playerId === lb.you!.playerId) && (                <div className="mt-4"><p className="label mb-2">You</p><LeaderboardList entries={[lb.you]} highlightId={sess?.playerId} /></div>)}            </motion.div>          )}
          {view === 'ended' && lb && (            <Center key="e">              {lb.you && lb.you.rank <= 3 && <Confetti />}              <h1 className="font-display text-4xl font-extrabold">Quiz completed</h1>              {lb.you && <div className="mt-6 w-full max-w-sm rounded-3xl bg-gradient-to-br from-brand-500 to-fuchsia-600 p-6 text-center">                <p className="text-sm uppercase tracking-wider opacity-80">Your result</p>                <p className="mt-2 font-display text-5xl font-extrabold">{ordinal(lb.you.rank)}</p>                <p className="mt-1 text-xl font-bold">{lb.you.score.toLocaleString()} pts · {lb.you.correct} correct</p></div>}              <div className="mt-6 w-full max-w-sm"><LeaderboardList entries={lb.top} highlightId={sess?.playerId} /></div>              <button className="btn-ghost mt-6" onClick={() => nav(`/results/${pin}`)}>View full results</button>            </Center>          )}
          {view === 'error' && <Center key="x"><p className="text-rose-400">{err}</p><button className="btn-primary mt-4" onClick={() => nav('/join')}>Back to join</button></Center>}        </AnimatePresence>      </section>    </main>  );}
const Center = ({ children }: { children: React.ReactNode }) => (  <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="flex flex-1 flex-col items-center justify-center text-center">{children}</motion.div>);const ordinal = (n: number) => `${n}${['th', 'st', 'nd', 'rd'][(n % 100 - 20) % 10] ?? ['th', 'st', 'nd', 'rd'][n % 100] ?? 'th'}`;
