import { Router } from 'express';import { z } from 'zod';import { pool } from '../database/pool';import { requireAuth, type AuthedRequest } from '../middleware/auth';import { validate } from '../middleware/validate';
const r = Router();r.use(requireAuth);
const questionSchema = z.object({  text: z.string().min(1).max(500),  imageUrl: z.string().url().nullable().optional(),  options: z.tuple([z.string().min(1).max(120), z.string().min(1).max(120), z.string().min(1).max(120), z.string().min(1).max(120)]),  correctIndex: z.number().int().min(0).max(3),  timeLimitSec: z.number().int().min(5).max(300).default(20),  points: z.number().int().min(0).max(10000).default(1000),});const quizSchema = z.object({  title: z.string().min(1).max(120),  description: z.string().max(1000).optional().default(''),  coverUrl: z.string().url().nullable().optional(),  settings: z.object({    scoringMode: z.enum(['FIXED', 'SPEED', 'NO_BONUS']).default('SPEED'),    shuffleQuestions: z.boolean().default(false),    shuffleAnswers: z.boolean().default(false),    allowNegative: z.boolean().default(false),    maxPlayers: z.number().int().min(1).max(10000).default(2000),  }).default({}),  questions: z.array(questionSchema).max(200).default([]),});
const mapQuiz = (q: any) => ({ id: q.id, title: q.title, description: q.description, coverUrl: q.cover_url,  settings: q.settings, createdAt: q.created_at, updatedAt: q.updated_at, questionCount: Number(q.question_count ?? 0), gameCount: Number(q.game_count ?? 0) });
async function saveQuestions(client: any, quizId: string, questions: z.infer<typeof questionSchema>[]) {  await client.query(`DELETE FROM questions WHERE quiz_id=$1`, [quizId]);  for (let i = 0; i < questions.length; i++) {    const q = questions[i];    await client.query(`INSERT INTO questions (quiz_id,"order",text,image_url,options,correct_index,time_limit_sec,points)      VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`, [quizId, i, q.text, q.imageUrl ?? null, JSON.stringify(q.options), q.correctIndex, q.timeLimitSec, q.points]);  }}
/* List */r.get('/', async (req, res, next) => {  try {    const { userId } = req as unknown as AuthedRequest;    const { rows } = await pool.query(`      SELECT q.*, (SELECT COUNT(*) FROM questions WHERE quiz_id=q.id) question_count,             (SELECT COUNT(*) FROM games WHERE quiz_id=q.id) game_count      FROM quizzes q WHERE owner_id=$1 ORDER BY updated_at DESC`, [userId]);    res.json(rows.map(mapQuiz));  } catch (e) { next(e); }});
/* Create */r.post('/', validate(quizSchema), async (req, res, next) => {  const client = await pool.connect();  try {    const { userId } = req as unknown as AuthedRequest; const b = req.body;    await client.query('BEGIN');    const { rows: [q] } = await client.query(`INSERT INTO quizzes (owner_id,title,description,cover_url,settings)      VALUES ($1,$2,$3,$4,$5) RETURNING *`, [userId, b.title, b.description, b.coverUrl ?? null, b.settings]);    await saveQuestions(client, q.id, b.questions);    await client.query('COMMIT');    res.status(201).json(mapQuiz(q));  } catch (e) { await client.query('ROLLBACK'); next(e); } finally { client.release(); }});
/* Read one (with questions incl. correct answers — owner only) */r.get('/:id', async (req, res, next) => {  try {    const { userId } = req as unknown as AuthedRequest;    const { rows: [q] } = await pool.query(`SELECT * FROM quizzes WHERE id=$1 AND owner_id=$2`, [req.params.id, userId]);    if (!q) return res.status(404).json({ error: 'Quiz not found' });    const { rows: qs } = await pool.query(`SELECT * FROM questions WHERE quiz_id=$1 ORDER BY "order"`, [q.id]);    res.json({ ...mapQuiz(q), questions: qs.map(x => ({ id: x.id, text: x.text, imageUrl: x.image_url, options: x.options,      correctIndex: x.correct_index, timeLimitSec: x.time_limit_sec, points: x.points })) });  } catch (e) { next(e); }});
/* Update */r.put('/:id', validate(quizSchema), async (req, res, next) => {  const client = await pool.connect();  try {    const { userId } = req as unknown as AuthedRequest; const b = req.body;    await client.query('BEGIN');    const { rows: [q] } = await client.query(`UPDATE quizzes SET title=$1,description=$2,cover_url=$3,settings=$4,updated_at=now()      WHERE id=$5 AND owner_id=$6 RETURNING *`, [b.title, b.description, b.coverUrl ?? null, b.settings, req.params.id, userId]);    if (!q) { await client.query('ROLLBACK'); return res.status(404).json({ error: 'Quiz not found' }); }    await saveQuestions(client, q.id, b.questions);    await client.query('COMMIT');    res.json(mapQuiz(q));  } catch (e) { await client.query('ROLLBACK'); next(e); } finally { client.release(); }});
/* Duplicate */r.post('/:id/duplicate', async (req, res, next) => {  const client = await pool.connect();  try {    const { userId } = req as unknown as AuthedRequest;    await client.query('BEGIN');    const { rows: [src] } = await client.query(`SELECT * FROM quizzes WHERE id=$1 AND owner_id=$2`, [req.params.id, userId]);    if (!src) return res.status(404).json({ error: 'Quiz not found' });    const { rows: [q] } = await client.query(`INSERT INTO quizzes (owner_id,title,description,cover_url,settings)      VALUES ($1,$2,$3,$4,$5) RETURNING *`, [userId, `${src.title} (copy)`, src.description, src.cover_url, src.settings]);    await client.query(`INSERT INTO questions (quiz_id,"order",text,image_url,options,correct_index,time_limit_sec,points)      SELECT $1,"order",text,image_url,options,correct_index,time_limit_sec,points FROM questions WHERE quiz_id=$2`, [q.id, src.id]);    await client.query('COMMIT');    res.status(201).json(mapQuiz(q));  } catch (e) { await client.query('ROLLBACK'); next(e); } finally { client.release(); }});
/* Delete */r.delete('/:id', async (req, res, next) => {  try {    const { userId } = req as unknown as AuthedRequest;    const { rowCount } = await pool.query(`DELETE FROM quizzes WHERE id=$1 AND owner_id=$2`, [req.params.id, userId]);    rowCount ? res.status(204).end() : res.status(404).json({ error: 'Quiz not found' });  } catch (e) { next(e); }});
export default r;
