import type { Server, Socket } from 'socket.io';import { GameService, GameError } from '../services/gameService';import { GameState } from '../redis/gameState';import { verifyFirebaseToken, userIdForUid } from '../middleware/auth';
const fail = (e: unknown) => e instanceof GameError  ? { ok: false as const, code: e.code, message: e.message }  : { ok: false as const, code: 'SERVER_ERROR', message: 'Server error' };
export function registerHostHandlers(io: Server, socket: Socket) {  const requireHost = async (pin: string) => {    const meta = await GameService.requireMeta(pin);    if (socket.data.role !== 'host' || socket.data.pin !== pin) throw new GameError('FORBIDDEN', 'Not the host of this game');    return meta;  };
  socket.on('host-join', async ({ pin, idToken }, cb) => {    try {      const decoded = await verifyFirebaseToken(idToken);      const userId = await userIdForUid(decoded.uid);      const meta = await GameService.requireMeta(pin);      if (meta.hostId !== userId) throw new GameError('FORBIDDEN', 'You are not the host of this game');
      socket.data = { pin, role: 'host', hostUid: decoded.uid };      await socket.join(`${pin}:host`);      await GameState.setHostSocket(pin, socket.id);      io.to(pin).emit('host-reconnected');
      const players = await GameState.allPlayers(pin);      const questions = await GameService.questions(pin);      const q = meta.questionIndex >= 0 ? questions[meta.questionIndex] : undefined;      cb({ ok: true, data: {        status: meta.status, quizTitle: meta.title, questionIndex: meta.questionIndex, totalQuestions: meta.totalQuestions,        participants: players.length,        answered: meta.questionIndex >= 0 ? await GameState.answeredCount(pin, meta.questionIndex) : 0,        question: q,        stats: q && ['STATS', 'LEADERBOARD', 'QUESTION_ENDED'].includes(meta.status)          ? { counts: await GameState.answerCounts(pin, meta.questionIndex), answered: 0, participants: players.length, correctIndex: q.correctIndex }          : undefined,      }});      socket.emit('lobby-snapshot', { players: players.map(p => ({ id: p.id, nickname: p.nickname })), count: players.length });    } catch (e) { cb(fail(e)); }  });
  const guarded = (fn: (pin: string) => Promise<unknown>) => async ({ pin }: { pin: string }, cb: (r: unknown) => void) => {    try { await requireHost(pin); await fn(pin); cb({ ok: true, data: null }); } catch (e) { cb(fail(e)); }  };
  socket.on('host-start-game',       guarded(pin => GameService.startGame(io, pin)));  socket.on('host-next-question',    guarded(pin => GameService.nextQuestion(io, pin)));  socket.on('host-end-question',     guarded(async pin => { const m = await GameState.meta(pin); if (m) await GameService.endQuestion(io, pin, m.questionIndex); }));  socket.on('host-show-results',     guarded(pin => GameService.showResults(io, pin)));  socket.on('host-show-leaderboard', guarded(pin => GameService.showLeaderboard(io, pin)));  socket.on('host-end-game',         guarded(pin => GameService.endGame(io, pin)));
  socket.on('host-kick-player', async ({ pin, playerId }, cb) => {    try {      await requireHost(pin);      const sockets = await io.in(pin).fetchSockets();      const target = sockets.find(s => s.data.playerId === playerId);      target?.emit('kicked'); target?.disconnect(true);      await GameState.removePlayer(pin, playerId);      io.to(`${pin}:host`).emit('player-left', { playerId, count: await GameState.playerCount(pin) });      cb({ ok: true, data: null });    } catch (e) { cb(fail(e)); }  });
  socket.on('disconnect', () => {    if (socket.data.role === 'host' && socket.data.pin) io.to(socket.data.pin).emit('host-disconnected');  });}
