import type { Server, Socket } from 'socket.io';import { GameService, GameError } from '../services/gameService';import { GameState } from '../redis/gameState';import { sanitizeNickname } from '../utils/nickname';import { verifyPlayerToken } from '../utils/playerToken';import { socketRateLimit } from './rateLimit';import { z } from 'zod';
const pinSchema = z.string().regex(/^\d{6}$/);const joinSchema = z.object({ pin: pinSchema, nickname: z.string().min(1).max(30) });const answerSchema = z.object({ pin: pinSchema, questionIndex: z.number().int().min(0), answer: z.number().int().min(0).max(3) });
const fail = (e: unknown) => e instanceof GameError  ? { ok: false as const, code: e.code, message: e.message }  : { ok: false as const, code: 'SERVER_ERROR', message: 'Something went wrong. Please try again.' };
export function registerPlayerHandlers(io: Server, socket: Socket) {  const ip = (socket.handshake.headers['x-forwarded-for'] as string)?.split(',')[0] ?? socket.handshake.address;
  socket.on('join-game', async (raw, cb) => {    try {      if (!(await socketRateLimit(`join:${ip}`, 10, 60))) throw new GameError('RATE_LIMIT', 'Too many attempts. Wait a minute.');      const { pin, nickname } = joinSchema.parse(raw);      const nick = sanitizeNickname(nickname);      if (!nick) throw new GameError('BAD_NICKNAME', 'Please choose a valid nickname');
      const { player, token, status } = await GameService.join(pin, nick, socket.id);      socket.data = { pin, playerId: player.id, role: 'player' };      await socket.join(pin);
      const count = await GameState.playerCount(pin);      io.to(`${pin}:host`).emit('player-joined', { player: { id: player.id, nickname: nick }, count });      socket.to(pin).emit('player-joined', { player: { id: player.id, nickname: nick }, count });      cb({ ok: true, data: { playerId: player.id, token, nickname: nick, status } });    } catch (e) { cb(fail(e)); }  });
  socket.on('reconnect-player', async (raw, cb) => {    try {      const { pin, token } = z.object({ pin: pinSchema, token: z.string() }).parse(raw);      const claims = verifyPlayerToken(token);      if (!claims || claims.pin !== pin) throw new GameError('EXPIRED_SESSION', 'Session invalid');      const r = await GameService.reconnect(pin, claims.playerId, socket.id);      socket.data = { pin, playerId: claims.playerId, role: 'player' };      await socket.join(pin);      cb({ ok: true, data: { playerId: r.player.id, nickname: r.player.nickname, status: r.status,        question: r.question, alreadyAnswered: r.alreadyAnswered, score: r.player.score, rank: r.rank } });    } catch (e) { cb(fail(e)); }  });
  socket.on('submit-answer', async (raw, cb) => {    try {      if (!(await socketRateLimit(`ans:${socket.id}`, 5, 2))) throw new GameError('RATE_LIMIT', 'Slow down');      const { pin, questionIndex, answer } = answerSchema.parse(raw);      const { playerId } = socket.data;      if (!playerId || socket.data.pin !== pin) throw new GameError('NOT_JOINED', 'You are not in this game');      await GameService.submitAnswer(io, pin, playerId, questionIndex, answer as 0 | 1 | 2 | 3);      cb({ ok: true, data: { accepted: true } });    } catch (e) { cb(fail(e)); }  });
  socket.on('disconnect', async () => {    const { pin, playerId, role } = socket.data;    if (role !== 'player' || !pin || !playerId) return;    await GameState.setConnected(pin, playerId, null).catch(() => {});    const count = await GameState.playerCount(pin).catch(() => 0);    io.to(`${pin}:host`).emit('player-left', { playerId, count });  });}
